// Generated by scripts/split_bangla_verses.py: do not edit.
package dev.sadakat.qit.core.domain.audio

import dev.sadakat.qit.core.domain.model.Track

/** See [SharedTranslations]. */
internal val SHARED_TRANSLATIONS: Map<Track, String> = mapOf(
    Track.BANGLA_TOHA to "",
    Track.BANGLA_BAEZEED to "",
)
