// Generated by scripts/split_bangla_verses.py: do not edit.
@file:Suppress("MaxLineLength") // one line of ranges per voice

package dev.sadakat.qit.core.domain.audio

import dev.sadakat.qit.core.domain.model.Track

/** See [SharedTranslations]. */
internal val SHARED_TRANSLATIONS: Map<Track, String> = mapOf(
    Track.BANGLA_TOHA to
        "6,3710-3711,3716,3718,3720-3722,3724,3727-3728,3731,3734,3738-3739,3744-3747,3753-3754,3759,3764,3771,3773,3775,3779-3781,3783-3787,5242-5243,5245-5248,5250,5252,5254,5256,5258-5261,5263,5268-5270,6226-6229",
    Track.BANGLA_BAEZEED to
        "3706,3767",
)
