package dev.sadakat.qit.shared.quran.text

import android.content.Context
import dev.sadakat.qit.shared.quran.model.Ayah
import dev.sadakat.qit.shared.quran.model.Surah

/** Quran text and surah metadata, bundled in the app (works offline). */
interface QuranText {

    /** All 114 surahs, in order. */
    suspend fun surahs(): List<Surah>

    suspend fun surah(number: Int): Surah

    /** Every ayah of [surah], in order, with Arabic, English and Bangla text. */
    suspend fun ayahs(surah: Int): List<Ayah>
}

/** [QuranText] read from `assets/quran/` (generated by `scripts/build_quran_text.py`). */
class AssetQuranText(private val context: Context) : QuranText {

    override suspend fun surahs(): List<Surah> = TODO("W1")

    override suspend fun surah(number: Int): Surah = TODO("W1")

    override suspend fun ayahs(surah: Int): List<Ayah> = TODO("W1")
}
