package dev.sadakat.qit.core.data.text

import android.content.Context
import dev.sadakat.qit.core.domain.model.QuranMeta
import dev.sadakat.qit.core.domain.model.WordByWord
import dev.sadakat.qit.core.domain.repository.WordMeanings
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.util.Locale

/**
 * [WordMeanings] read from `assets/quran/words/{en|bn}/001..114.json` (generated by
 * `scripts/build_word_meanings.py`).
 */
class AssetWordMeanings(private val context: Context) : WordMeanings {

    /** Meanings of a handful of recently used surahs are kept in memory, per language. */
    private val maxCachedEntries = 4

    /** Access-ordered: the least recently read language/surah pair is evicted by [LinkedHashMap.removeEldestEntry]. */
    private val cache = object : LinkedHashMap<Pair<WordByWord, Int>, Map<Int, List<String>>>(8, 0.75f, true) {
        override fun removeEldestEntry(
            eldest: MutableMap.MutableEntry<Pair<WordByWord, Int>, Map<Int, List<String>>>,
        ): Boolean = size > maxCachedEntries
    }
    private val cacheMutex = Mutex()

    override suspend fun meanings(surah: Int, language: WordByWord): Map<Int, List<String>> {
        require(surah in 1..QuranMeta.SURAH_COUNT) { "Invalid surah $surah" }
        if (language == WordByWord.OFF) return emptyMap()
        val key = language to surah
        cacheMutex.withLock { cache[key]?.let { return it } }
        val ayahs = parseAsset(assetPath(language, surah))
        // The basmala before verse 1 is 1:1's meanings (Al-Fatiha has none, so no recursion).
        val meanings = when {
            QuranMeta.hasBasmalaPrefix(surah) -> ayahs + (0 to meanings(1, language).getValue(1))
            else -> ayahs
        }
        cacheMutex.withLock { cache[key] = meanings }
        return meanings
    }

    /** Word meaning files are named `001.json` … `114.json` under the language's folder. */
    private fun assetPath(language: WordByWord, surah: Int) = when (language) {
        WordByWord.ENGLISH -> "quran/words/en"
        WordByWord.BANGLA -> "quran/words/bn"
        WordByWord.OFF -> error("OFF has no word meanings") // Unreachable: OFF returns above.
    } + "/" + String.format(Locale.ROOT, "%03d", surah) + ".json"

    /** Reads and parses an asset off the caller's thread: the reader asks from the main thread. */
    private suspend fun parseAsset(path: String): Map<Int, List<String>> = withContext(Dispatchers.IO) {
        WordMeaningsParser.parse(context.assets.open(path).bufferedReader().use { it.readText() })
    }
}
