package dev.sadakat.qit.core.data.text

import android.content.Context
import dev.sadakat.qit.core.domain.model.Ayah
import dev.sadakat.qit.core.domain.model.QuranMeta
import dev.sadakat.qit.core.domain.model.Surah
import dev.sadakat.qit.core.domain.repository.QuranText
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.util.Locale

/** [QuranText] read from `assets/quran/` (generated by `scripts/build_quran_text.py`). */
class AssetQuranText(private val context: Context) : QuranText {

    /** Text for a handful of recently used surahs is kept in memory; Al-Baqarah alone is ~1 MB. */
    private val maxCachedSurahs = 6

    private val surahsMutex = Mutex()
    private var cachedSurahs: List<Surah>? = null

    /** Access-ordered map: the least recently read surah is evicted by [LinkedHashMap.removeEldestEntry]. */
    private val cachedAyahs = object : LinkedHashMap<Int, List<Ayah>>(16, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<Int, List<Ayah>>): Boolean =
            size > maxCachedSurahs
    }
    private val ayahsMutex = Mutex()

    override suspend fun surahs(): List<Surah> = surahsMutex.withLock {
        cachedSurahs ?: QuranTextParser.parseSurahs(readAsset("quran/surahs.json")).also { cachedSurahs = it }
    }

    override suspend fun surah(number: Int): Surah {
        require(number in 1..QuranMeta.SURAH_COUNT) { "Invalid surah $number" }
        return surahs().firstOrNull { it.number == number }
            ?: throw IllegalArgumentException("No surah $number in surahs.json")
    }

    override suspend fun ayahs(surah: Int): List<Ayah> {
        require(surah in 1..QuranMeta.SURAH_COUNT) { "Invalid surah $surah" }
        // Hit: serve from the cache without parsing.
        ayahsMutex.withLock { cachedAyahs[surah]?.let { return it } }
        // Miss: parse outside the lock so concurrent readers of other surahs are not blocked.
        val ayahs = QuranTextParser.parseAyahs(surah, readAsset("quran/text/${fileName(surah)}.json"))
        ayahsMutex.withLock { cachedAyahs[surah] = ayahs }
        return ayahs
    }

    /** Surah text files are named `001.json` … `114.json`. */
    private fun fileName(surah: Int): String = String.format(Locale.ROOT, "%03d", surah)

    private suspend fun readAsset(path: String): String = withContext(Dispatchers.IO) {
        context.assets.open(path).bufferedReader().use { it.readText() }
    }
}
