package dev.sadakat.qit.core.data.text

import android.content.Context
import dev.sadakat.qit.core.domain.model.Ayah
import dev.sadakat.qit.core.domain.model.Surah
import dev.sadakat.qit.core.domain.repository.QuranText

/** [QuranText] read from `assets/quran/` (generated by `scripts/build_quran_text.py`). */
class AssetQuranText(private val context: Context) : QuranText {

    override suspend fun surahs(): List<Surah> = TODO("W1")

    override suspend fun surah(number: Int): Surah = TODO("W1")

    override suspend fun ayahs(surah: Int): List<Ayah> = TODO("W1")
}
