package dev.sadakat.qit.core.data.text

import dev.sadakat.qit.core.domain.model.Ayah
import dev.sadakat.qit.core.domain.model.QuranMeta
import dev.sadakat.qit.core.domain.model.Revelation
import dev.sadakat.qit.core.domain.model.Surah
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json

/**
 * Parses the compact JSON assets under `assets/quran/` (generated by `scripts/build_quran_text.py`)
 * into domain models. Pure Kotlin, no Android, so it is cheap to test on the JVM.
 */
internal object QuranTextParser {

    private val decoder = Json { ignoreUnknownKeys = true }

    @Serializable
    private data class SurahDto(
        val number: Int,
        val nameArabic: String,
        val nameEnglish: String,
        val meaningEnglish: String,
        val ayahCount: Int,
        val revelation: String,
    )

    @Serializable
    private data class AyahDto(val n: Int, val g: Int, val ar: String, val en: String, val bn: String)

    /**
     * @throws IllegalArgumentException if the JSON is not a valid surah list
     * (`SerializationException` is an `IllegalArgumentException`, but wrapping it adds the
     * "which asset" context to the message).
     */
    fun parseSurahs(json: String): List<Surah> = try {
        decoder.decodeFromString<List<SurahDto>>(json).map { it.toSurah() }
    } catch (e: SerializationException) {
        throw IllegalArgumentException("Malformed surah list", e)
    }

    /** @throws IllegalArgumentException if [surah] is not in 1..114 or the JSON is not a valid ayah list. */
    fun parseAyahs(surah: Int, json: String): List<Ayah> {
        require(surah in 1..QuranMeta.SURAH_COUNT) { "Invalid surah $surah" }
        return try {
            decoder.decodeFromString<List<AyahDto>>(json).map { it.toAyah(surah) }
        } catch (e: SerializationException) {
            throw IllegalArgumentException("Malformed ayah list for surah $surah", e)
        }
    }

    private fun SurahDto.toSurah() = Surah(
        number = number,
        nameArabic = nameArabic,
        nameEnglish = nameEnglish,
        meaningEnglish = meaningEnglish,
        ayahCount = ayahCount,
        revelation = Revelation.valueOf(revelation),
    )

    private fun AyahDto.toAyah(surah: Int) = Ayah(
        surah = surah,
        number = n,
        globalNumber = g,
        arabic = ar,
        english = en,
        bangla = bn,
    )
}
