#!/usr/bin/env python3
"""Generates the non-brand tonal palettes into ref/QItPalettes.kt (core/designsystem).

Every palette is an HCT (Material Color Utilities) tonal palette: a tone is the same CIE L* in
every palette, so tone contrast predicts text contrast. The brand tables in that file (primary,
secondary, tertiary, neutral, neutralVariant, error — the mushaf seeds) are the script's context,
not its output: only the marked region at the bottom is rewritten, holding

  baselinePrimary..baselineNeutralVariant - Material 3's baseline from its seed #6750A4, with the
      standard (non-content) CorePalette rules: primary chroma 48, secondary 16, tertiary 24 at the
      seed hue rotated 60 degrees, neutral 4, neutralVariant 8. The error palette is Material's
      standard error hue, so the brand's error table is reused.
  sepiaNeutral / sepiaNeutralVariant - the sepia page's paper and ink (hue 95, chroma 8 / 16),
      tuned so tone 94 reads like a classic sepia e-reader's paper (near #F4ECD8; the hue 75,
      chroma 12 first guess is noticeably more orange at that tone).

Tones are Material's tone list; the sepia pair also carries 84, 85, 86 and 88, where the sepia
page's container surfaces sit.

The tones come from materialyoucolor, the Python port of Material Color Utilities. It is not a
project dependency, so install it into a throwaway venv and run the script with that interpreter:
  python3 -m venv /tmp/qit-palettes-venv
  /tmp/qit-palettes-venv/bin/pip install materialyoucolor
  /tmp/qit-palettes-venv/bin/python scripts/build_palettes.py

Usage (from the repo root):
  python3 scripts/build_palettes.py
Tests (pure functions only, no materialyoucolor needed):
  python3 -m unittest scripts/test_build_palettes.py -v
"""
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PALETTES_KT = os.path.join(
    REPO, "core", "designsystem", "src", "main", "kotlin", "dev", "sadakat", "qit", "core",
    "designsystem", "ref", "QItPalettes.kt",
)

BASELINE_SEED = 0xFF6750A4
SEPIA_HUE = 95.0
SEPIA_NEUTRAL_CHROMA = 8.0
SEPIA_NEUTRAL_VARIANT_CHROMA = 16.0
SEPIA_PAPER_TONE = 94
SEPIA_PAPER_ANCHOR = 0xFFF4ECD8

TONES = (0, 4, 6, 10, 12, 15, 17, 20, 22, 24, 25, 30, 35, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100)
# The sepia page's containers sit between the standard tones.
SEPIA_EXTRA_TONES = (84, 85, 86, 88)

REGION_START = "// region generated by scripts/build_palettes.py"
REGION_END = "// endregion generated by scripts/build_palettes.py"


def generate(tonal_palette, core_palette):
    """The palettes to emit: [(name, doc, tones), ...] with tones as [(tone, argb), ...].

    `tonal_palette` and `core_palette` are materialyoucolor's TonalPalette and CorePalette classes,
    passed in so importing this module needs neither.
    """
    core = core_palette.of(BASELINE_SEED)
    hue = tonal_palette.from_int(BASELINE_SEED).get_hct(40).hue

    def at(name, tones):
        palette = getattr(core, name) if isinstance(name, str) else tonal_palette.from_hue_and_chroma(*name)
        return [(tone, palette.tone(tone)) for tone in tones]

    return [
        (
            "baselinePrimary",
            "Material 3's baseline purple — its seed #6750A4 (hue %d, chroma 48)." % round(hue),
            at("a1", TONES),
        ),
        (
            "baselineSecondary",
            "The baseline's quieter purple for secondary containers (hue %d, chroma 16)." % round(hue),
            at("a2", TONES),
        ),
        (
            "baselineTertiary",
            "The baseline's counterpoint — the seed hue rotated 60 degrees (hue %d, chroma 24)." % round(hue + 60),
            at("a3", TONES),
        ),
        (
            "baselineNeutral",
            "The baseline's surfaces and body text (hue %d, chroma 4)." % round(hue),
            at("n1", TONES),
        ),
        (
            "baselineNeutralVariant",
            "The baseline's outlines and secondary text (hue %d, chroma 8)." % round(hue),
            at("n2", TONES),
        ),
        (
            "sepiaNeutral",
            "Sepia paper and ink — the warm page of a classic e-reader (hue %d, chroma %d; tone %d is "
            "near #%06X)." % (SEPIA_HUE, SEPIA_NEUTRAL_CHROMA, SEPIA_PAPER_TONE, SEPIA_PAPER_ANCHOR & 0xFFFFFF),
            at((SEPIA_HUE, SEPIA_NEUTRAL_CHROMA), sepia_tones()),
        ),
        (
            "sepiaNeutralVariant",
            "Sepia paper, slightly stronger — outlines and secondary text (hue %d, chroma %d)."
            % (SEPIA_HUE, SEPIA_NEUTRAL_VARIANT_CHROMA),
            at((SEPIA_HUE, SEPIA_NEUTRAL_VARIANT_CHROMA), sepia_tones()),
        ),
    ]


def sepia_tones():
    return tuple(sorted(TONES + SEPIA_EXTRA_TONES))


def kotlin_palette(name, doc, tones):
    """One Kotlin `val` block in the style of the brand tables."""
    lines = ["    /** %s */" % doc, "    val %s = TonalPalette(" % name, "        mapOf("]
    lines += ["            %d to Color(0x%08X)," % (tone, argb) for tone, argb in tones]
    lines += ["        ),", "    )"]
    return "\n".join(lines)


def generated_region(blocks):
    """The whole region, markers included, as it sits inside `object QItPalettes`."""
    return "    %s\n\n%s\n\n    %s" % (REGION_START, "\n\n".join(blocks), REGION_END)


def replace_region(source, region):
    """Puts [region] between the region markers of QItPalettes.kt's [source]; everything outside
    the markers stays byte-identical. Raises ValueError when the markers are missing or unpaired."""
    lines = source.split("\n")
    starts = [i for i, line in enumerate(lines) if line.strip() == REGION_START]
    ends = [i for i, line in enumerate(lines) if line.strip() == REGION_END]
    if len(starts) != 1 or len(ends) != 1 or starts[0] >= ends[0]:
        raise ValueError(
            "%s: expected exactly one '%s' line before one '%s' line"
            % (os.path.basename(PALETTES_KT), REGION_START, REGION_END)
        )
    return "\n".join(lines[: starts[0]] + region.split("\n") + lines[ends[0] + 1 :])


def main():
    try:
        from materialyoucolor.palettes.core_palette import CorePalette
        from materialyoucolor.palettes.tonal_palette import TonalPalette
    except ImportError as e:
        raise SystemExit(
            "materialyoucolor is needed to generate the palettes (see the docstring for a venv recipe)"
        ) from e

    palettes = generate(TonalPalette, CorePalette)
    blocks = [kotlin_palette(name, doc, tones) for name, doc, tones in palettes]
    with open(PALETTES_KT, encoding="utf-8") as f:
        source = f.read()
    with open(PALETTES_KT, "w", encoding="utf-8") as f:
        f.write(replace_region(source, generated_region(blocks)))
    print("Wrote %d palettes into the generated region of %s" % (len(palettes), PALETTES_KT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
