package dev.sadakat.qit.core.data.audio

import android.content.Context
import android.util.Log
import dev.sadakat.qit.core.domain.audio.WordTimings
import dev.sadakat.qit.core.domain.model.QuranMeta
import dev.sadakat.qit.core.domain.model.Track
import dev.sadakat.qit.core.domain.repository.AudioTimings
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.FileNotFoundException
import java.util.Locale

/**
 * [AudioTimings] read from `assets/quran/audio/durations.json` and `assets/quran/timing/<dir>/`
 * (generated by `scripts/build_audio_timing.py`). Word timings are per Arabic reciter; a reciter
 * whose timings are not bundled yet (or a translation track, which has none) yields an empty map.
 */
class AssetAudioTimings(private val context: Context) : AudioTimings {

    /** Word timings of a handful of recently used reciter/surah pairs are kept in memory. */
    private val maxCachedSurahs = 4

    private val durationsMutex = Mutex()
    private var durations: AudioDurations? = null

    private val timingsMutex = Mutex()
    private val cachedTimings =
        object : LinkedHashMap<Pair<Track, Int>, Map<Int, WordTimings>>(8, 0.75f, true) {
            override fun removeEldestEntry(
                eldest: MutableMap.MutableEntry<Pair<Track, Int>, Map<Int, WordTimings>>,
            ): Boolean = size > maxCachedSurahs
        }

    override suspend fun wordTimings(surah: Int, reciter: Track): Map<Int, WordTimings> {
        if (!reciter.isArabic) return emptyMap()
        require(surah in 1..QuranMeta.SURAH_COUNT) { "Invalid surah $surah" }
        timingsMutex.withLock { cachedTimings[reciter to surah]?.let { return it } }
        val ayahs = try {
            parseAsset(timingPath(reciter, surah), AudioTimingParser::parseWordTimings)
        } catch (e: FileNotFoundException) {
            // A reciter whose timings the pipeline has not bundled yet.
            Log.i(TAG, "No bundled word timings for ${reciter.code} surah $surah", e)
            emptyMap()
        }
        // The basmala before verse 1 is recited from 1:1's file (Al-Fatiha has none, so no recursion).
        val basmala = if (QuranMeta.hasBasmalaPrefix(surah)) wordTimings(1, reciter)[1] else null
        val timings = if (basmala == null) ayahs else ayahs + (0 to basmala)
        timingsMutex.withLock { cachedTimings[reciter to surah] = timings }
        return timings
    }

    override suspend fun durationMs(fileId: String): Long? {
        val all = durationsMutex.withLock {
            durations ?: parseAsset(DURATIONS, AudioTimingParser::parseDurations).also { durations = it }
        }
        return all.durationMs(fileId)
    }

    /** Where [reciter]'s word timings live, e.g. `quran/timing/ar.alafasy/002.json`. */
    private fun timingPath(reciter: Track, surah: Int) =
        "quran/timing/${reciter.timingDir}/" + String.format(Locale.ROOT, "%03d", surah) + ".json"

    /** Reads and parses an asset off the caller's thread: the player asks from the main thread. */
    private suspend fun <T> parseAsset(path: String, parse: (String) -> T): T = withContext(Dispatchers.IO) {
        parse(context.assets.open(path).bufferedReader().use { it.readText() })
    }

    private val Track.timingDir: String
        get() = when (this) {
            Track.ARABIC -> "ar.alafasy"

            Track.ARABIC_BASIT_MUJAWWAD -> "ar.basit-mujawwad"

            Track.ARABIC_SUDAIS -> "ar.sudais"

            // Only Arabic tracks reach here (wordTimings returns early for the rest).
            else -> error("$code has no word timings")
        }

    private companion object {
        const val DURATIONS = "quran/audio/durations.json"
        const val TAG = "AssetAudioTimings"
    }
}
