package dev.sadakat.qit.core.data.audio

import android.content.Context
import dev.sadakat.qit.core.domain.audio.WordTimings
import dev.sadakat.qit.core.domain.model.QuranMeta
import dev.sadakat.qit.core.domain.repository.AudioTimings
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.util.Locale

/**
 * [AudioTimings] read from `assets/quran/audio/durations.json` and `assets/quran/timing/ar.alafasy/`
 * (generated by `scripts/build_audio_timing.py`).
 */
class AssetAudioTimings(private val context: Context) : AudioTimings {

    /** Word timings of a handful of recently used surahs are kept in memory. */
    private val maxCachedSurahs = 4

    private val durationsMutex = Mutex()
    private var durations: AudioDurations? = null

    private val timingsMutex = Mutex()
    private val cachedTimings = object : LinkedHashMap<Int, Map<Int, WordTimings>>(8, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<Int, Map<Int, WordTimings>>): Boolean =
            size > maxCachedSurahs
    }

    override suspend fun wordTimings(surah: Int): Map<Int, WordTimings> {
        require(surah in 1..QuranMeta.SURAH_COUNT) { "Invalid surah $surah" }
        timingsMutex.withLock { cachedTimings[surah]?.let { return it } }
        val ayahs = parseAsset(timingPath(surah), AudioTimingParser::parseWordTimings)
        // The basmala before verse 1 is recited from 1:1's file (Al-Fatiha has none, so no recursion).
        val timings = if (QuranMeta.hasBasmalaPrefix(surah)) ayahs + (0 to wordTimings(1).getValue(1)) else ayahs
        timingsMutex.withLock { cachedTimings[surah] = timings }
        return timings
    }

    override suspend fun durationMs(fileId: String): Long? {
        val all = durationsMutex.withLock {
            durations ?: parseAsset(DURATIONS, AudioTimingParser::parseDurations).also { durations = it }
        }
        return all.durationMs(fileId)
    }

    private fun timingPath(surah: Int) =
        "quran/timing/ar.alafasy/" + String.format(Locale.ROOT, "%03d", surah) + ".json"

    /** Reads and parses an asset off the caller's thread: the player asks from the main thread. */
    private suspend fun <T> parseAsset(path: String, parse: (String) -> T): T = withContext(Dispatchers.IO) {
        parse(context.assets.open(path).bufferedReader().use { it.readText() })
    }

    private companion object {
        const val DURATIONS = "quran/audio/durations.json"
    }
}
